WebATB/WebATB/ViewComponents/UserLinkViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebATB.Data.Entities.Idenity;
using WebATB.Models.Account;

namespace WebATB.ViewComponents;

public class UserLinkViewComponent(UserManager<UserEntity> userManager,
    IMapper mapper) : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        var userName = User.Identity?.Name ;
        var model = new UserLinkViewModel();

        if(userName != null)
        {
            var user = userManager.FindByNameAsync(userName).Result;
            if(user != null)
            {
                model = mapper.Map<UserLinkViewModel>(user);
            }
        }
        return View(model);
    }
}

WebATB/WebATB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebATB</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/admin/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/admin/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/admin/WebATB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebATB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebATB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/admin/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/admin/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/admin/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebATB/WebATB/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="/cat.png" />
    <title>WebATB</title>
    <link href="/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="/css/site.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Main")">АТБ</a>
                <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarCollapse" style="">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Products">Продукти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                        </li>
                    </ul>
                    @* <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form> *@
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav">
                            @await Component.InvokeAsync("UserLink")

                            <li class="nav-item">
                                <a class="nav-link" asp-action="Logout"
                                   asp-controller="Account">Вихід</a>
                            </li>
                        </ul>
                    }
                    else
                    {

                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Register" 
                                asp-controller="Account">Реєстрація</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>


    <div class="container">

        @RenderBody()

    </div>



    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>